# site
url: "https://example.github.io"
title: "Simplicity"
author: "John Doe"
permalink: "/:title/"
description: ""
keywords: 
  - blog

# header
logo_image: "/assets/images/logo.png"
search_enabled: true
home_enabled: true
about_enabled: true

# footer
sitemap_enabled: true
feed_enabled: true

# homepage
homepage:
  welcome:
    title: "Welcome to Simplicity"
    subtitle: "A clean and minimalistic Jekyll theme for writing and sharing your thoughts."

# about
about:
  author_name: "John Doe"
  author_image: "/assets/images/author.jpg"
  social_media_enabled: true

# social media
social_media:
  email: "example@mail.com"
  linkedin: "example"
  github: "example"
  youtube: "example"
  twitter: "example"
  instagram: "example"

# giscus (disqus alternative)
giscus: true

# disqus
disqus:
  shortname: "example"

# plugins
plugins:
  - jekyll-postcss
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# jekyll-paginate
paginate: 5
paginate_path: '/page/:num/'

# jekyll-postcss
postcss:
  cache: false

# exclude from build
exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

